### PR TITLE
Fixes Sk.killableWhile performance issues

### PR DESCRIPTION
**Pull request by waywaaard**
This PR replaces the window.timeout approach with a postMessage approach. My test have shown, that all is working.

The patch does not work on the normal run and only in the browser. I had to guard the window.postMessage calls in order to make closure and v8 happy.

@albertjan Should we put the checks with Sk.browser?

### CODE REVIEW

**Comment by brianpmarks** [comment]
Nice! Works for me.

**Comment by albertjan** [comment]
You mean if a browser supports `postMessage`?

**Comment by albertjan** [comment]
Great find btw.

**Comment by eah13** [comment]
Beautiful.  This is a huge performance increase: from 4.6s to 0.2s on my setup, which means only 20x slower than non-killable while vs ~450x before.

That said, there's still the original problem in https://github.com/trinketapp/trinket/issues/1357 of joystick events not getting into the event buffer somehow.  I'm wondering if there's something about the suspensions that prevents our custom FB device from handling (all of) them?  I've got to press the keys 2-3 times for every one that actually gets handled in the loop.

**Comment by waywaaard** [comment]
I am going to tackle this, while I try to implement the new sense-stick API

**Comment by waywaaard** [comment]
I've added a new performance fix in the `new_sense_hat_api` PR #26

**Comment by eah13** [comment]
@waywaaard should this PR be merged or closed?

**Pull request closed without merging**
