### PR TITLE
With, finally, py3 tests, kwargs for dict()

### PR DESCRIPTION
**Pull request by eah13**
Another upstream merge since skulpt is so 🔥 right now

@albertjan there are 4-5 lines of conflicts in compile.js that it seemed like a bad idea for me to try to resolve.  Would you mind hitting those whenever you're able?

`with` is so close I can taste it!

### CODE REVIEW

**Comment by albertjan** [comment]
I'm just about to head to bed but I'll do it tomorrow! :smile:

**Comment by albertjan** [comment]
hmmm finally, this should do the trick @eah13

**Comment by albertjan** [comment]
aaarg, if you resolve the conflicts of this PR on github, you push to skulpt/master! haha oops.... I'll have to open a new PR from a separate branch.

**Comment by eah13** [comment]
Closed in favor of #44

**Pull request closed without merging**
