### PR TITLE
Merge upstream

### PR DESCRIPTION
**Pull request by albertjan**
In chronological order:
- https://github.com/skulpt/skulpt/pull/581 -> Update assertAlmostEqual and assertNotAlmostEqual to more closely mat… 
- https://github.com/skulpt/skulpt/pull/580 -> Descriptors
- https://github.com/skulpt/skulpt/pull/586 -> Readme link update. Fixes #539
- https://github.com/skulpt/skulpt/pull/588 -> Run setTimeout within the global context.
- https://github.com/skulpt/skulpt/pull/582 -> Revert "Descriptors"
- https://github.com/skulpt/skulpt/pull/594 -> remapToPy() maps null to 'None' rather than '{}' **(may break our ast module)**
- https://github.com/skulpt/skulpt/pull/578 -> Use test.test_support to be compatible with CPython.
- https://github.com/skulpt/skulpt/pull/595 -> Better/More consistent handling of feedback. **(does the checks feature use the setup function?)**
- https://github.com/skulpt/skulpt/pull/592 -> Prefix internal names with $
- https://github.com/skulpt/skulpt/pull/598 -> More builtins (callable, next, iter)
- https://github.com/skulpt/skulpt/pull/599 -> Fix tiny typos
- https://github.com/skulpt/skulpt/pull/597 -> Normalise implicit calls **(moar suspendable stuff, check turtle suspension error)**
- https://github.com/skulpt/skulpt/pull/607 -> Add math.isinf function
- https://github.com/skulpt/skulpt/pull/608 -> Support catching multiple types of exceptions in an 'except' block
- https://github.com/skulpt/skulpt/pull/604 -> Minor v8 speedups
- https://github.com/skulpt/skulpt/pull/600 -> Rename ParseError to SyntaxError **(do we need to change something in wrapper for this?)**
- https://github.com/skulpt/skulpt/pull/593 -> decorators-2
- https://github.com/skulpt/skulpt/pull/611 -> Bugfix: Explicitly (re)declare all suspendable temporary variables
- https://github.com/skulpt/skulpt/pull/610 -> Wrap compiler output in a function to avoid scope gensyms colliding (not a problem for us, as far as I know)
- https://github.com/skulpt/skulpt/pull/612 -> fix comment for importBuiltinWithBody 
- https://github.com/skulpt/skulpt/pull/613 -> copy module
- https://github.com/skulpt/skulpt/pull/614 -> add pure python staticmethod and tests
- https://github.com/skulpt/skulpt/pull/630 -> Fix `brun` command
- https://github.com/skulpt/skulpt/pull/632 -> return .instance from ensureAnonymous 
- https://github.com/skulpt/skulpt/pull/643 -> make urllib use suspensions
- https://github.com/skulpt/skulpt/pull/641 -> corrected error on regex with assignments (repl we don't use this I think but we should check trinkets regex)
- https://github.com/skulpt/skulpt/pull/653 -> removed unnecessary console logs
- https://github.com/skulpt/skulpt/pull/654 -> Fix blog link
- https://github.com/skulpt/skulpt/pull/656 -> error in repl.js with comments 
- https://github.com/skulpt/skulpt/pull/657 -> Make in-place operations fall back to normal binary ops
- https://github.com/skulpt/skulpt/pull/658 -> Make closures work with keyword argument matching
- https://github.com/skulpt/skulpt/pull/659 -> Add type checking to set methods.
- https://github.com/skulpt/skulpt/pull/634 -> Move `__getattr__` and friends into instance `tp$getattr()` and friends
- https://github.com/skulpt/skulpt/pull/635 -> Support `__new__` in object construction
- https://github.com/skulpt/skulpt/pull/636 -> Add `datetime` module
- https://github.com/skulpt/skulpt/pull/660 -> Make dunder lookup use `tp$getattr()` again. Gives us better error messages.
- https://github.com/skulpt/skulpt/pull/662 -> Change dependencies to devDependencies
- https://github.com/skulpt/skulpt/pull/663 -> Fix conversion from longs to floats
- https://github.com/skulpt/skulpt/pull/664 -> Add npm scripts
- https://github.com/skulpt/skulpt/pull/665 -> Change all uses of performance to window.performance
- https://github.com/skulpt/skulpt/pull/671 -> fix reserved words in get and set attr
- https://github.com/skulpt/skulpt/pull/677 -> Add `args` attribute to standard exceptions
- https://github.com/skulpt/skulpt/pull/679 -> typo
- https://github.com/skulpt/skulpt/pull/686 -> fix args.length check, add tmp.js to .gitignore
- https://github.com/skulpt/skulpt/pull/687 -> update node
- https://github.com/skulpt/skulpt/pull/691 -> Implement explicit dunder-functions in list class
- https://github.com/skulpt/skulpt/pull/693 -> Platform Module

### CODE REVIEW

**Comment by eah13** [comment]
I checked over about 20 trinkets and didn't see any regressions ❇️ .  Hard to prove a negative, though, so probably worth coming up with a targeted example or two, as noted below.  I'm not 100% sure in all cases what the best code to test would be so I mostly used old code I had in the dev DB from previous bugs.

- [ ] remaptoPy(): My ast module checks seem to work identically http://elliott-dev.trinket.io/python/8b6ccc9389  I don't know where specifically the None/{} difference would show up though. **Perhaps we can get a targeted example here?**
- [x] Better Feedback: we use the correctly titled `setUp` function in the checks module, so the better handling works as-is AFAICT
- [ ] Implicit Calls: Not seeing any strange turtle errors. I mainly used this code, which used to fail silently but was fixed in the past: http://elliott-dev.trinket.io/python/f6aa4a29f7  **targeted example perhps?**
- [x] SyntaxError: Works fine, no change needed 

Nice work on this!  Sorry it took me a while to look over

**Comment by albertjan** [comment]
Wow thanks @eah13 for the tests! 

the `remapToPy` function isn't called anywhere in trinket and you can't call it from python, and our ast module has it's own tweaked version of `remapToPy` so I'm pretty sure we won't run into any problems with this.

Implicit calls. I misinterpreted the impact this might have on the turtle module, I've tried to find a targeted example with the turtle module and I couldn't. This explains better what will be fixed with this change:

```py
import time

class Test(object):
    def __len__(self):
        time.sleep(1)
        return 42
        
        
a = Test()
len(a)
```

**Comment by brianpmarks** [comment]
@albertjan Is your example supposed to throw a SuspensionError? I'm getting `SuspensionError: Cannot call a function that blocks or suspends here on line 10 in main.py`. FWIW, I get the same thing on master.

**Comment by albertjan** [comment]
Not anymore after this has been merged... if it does, I'll look into it. I thought this was supossed to be fixed by that PR from meredydd.

**Comment by albertjan** [comment]
From the PR:

> Most of this PR only affects the call paths for user-defined __len__ functions. I take it therefore that you are objecting to the modifications to Sk.builtin.len()?

**Comment by waywaaard** [comment]
Well, it does not throw on skulpt master and on my current build which has all new skulpt changes.

**Comment by albertjan** [comment]
Ah so the merge went a little wrong

**Comment by brianpmarks** [comment]
Hmm, I'm seeing the error in my environment on skulpt master. I've checked git logs and everything seems to be there and I'm fairly sure I'm building things correctly (although there's always a chance I'm screwing it up.) Perhaps there's something about our wrapper or skulpt config that could be causing this?

**Comment by waywaaard** [comment]
Hmm, at least it does work on my build and I've merged all upstream changes and the new suspension stuff.

**Comment by brianpmarks** [comment]
Ok. @waywaaard would you mind sharing your skulpt config and how you call `Sk.importMainWithBody` so I can compare with what we've got in our [wrapper.js](https://github.com/trinketapp/trinket/blob/develop/public/js/skulpt/wrapper.js)?

**Comment by waywaaard** [comment]
This is my current setup for skulpt.
```
 run() {
    if (this.isRunning()) {
      return;
    }

    this.config = this.project.config;
    this.files = this.project.getFiles();

    // Reset annotations
    this.files.forEach((file) => {
      file.setAnnotations([]);
    });

    let emitChange = () => {
      process.nextTick(() => {
        this.project.emitChange();
      });
    };

    emitChange();

    // Check for python2/python3
    let isPython3 = this.project.data.meta.language === 'python3';

    // Create a new canvas
    this.canvas = this.getOrCreateCanvasContainer();
    (Sk.TurtleGraphics || (Sk.TurtleGraphics = {width: 800, height: 600})).target = this.canvas;
    Sk.onAfterImport = this.onAfterImport.bind(this);

    // ToDo: add timeout handling here, skulpt reset stuff
    Sk.configure({
      output: text => {
        this._output(text);
      },
      inputfun: this.readPrompt.bind(this),
      read: x => {
        return this.defaultFileRead(x);
      },
      fileread: (x, mode) => {
        return this._fileRead(x, mode);
      },
      filewrite: (pyFile, x) => {
        this._fileWrite(pyFile, x);
      },
      fileopen: pyFile => {
        //console.info(pyFile);
      },
      nonreadopen: true,
      python3: isPython3,
      execLimit: null,/*RUN_DEFAULTS.execLimit,*/
      killableWhile: true,
      killableFor: true
    });

    this.stdoutTransform = new TerminalTransform();
    this.stdoutTransform.pipe(this.stdout, {end: false});

    // Wrap Skulpt native Promise with Bluebird
    this.promiseChain = this._exec()
    .tap(this._done.bind(this))
    .catch(this.handleSkulptError.bind(this))
    .finally(() => {
      //this.stdout.end();
      emitChange();
    });
  }

  _exec() {
    if (!this.config.exec) {
      throw new Error('No exec command');
    }

    let command = ['python3']; //this._commandArray(this.config.exec);

    let mainFile = this.getMainFile();

    let runEvent = new EventLog(EventLog.NAME_RUN, { execCommand: [command, mainFile].join(' ') });
    this.project.sendEvent(runEvent);

    this._status(command.join(' '), false); // output run call

    let processPromise = new Bluebird((resolve, reject) => {
      Sk.misceval.asyncToPromise(() => {
        return Sk.importMainWithBody(mainFile.name.replace('.py',''), false, mainFile.code, true);
      }, {'*': this.handleInterrupt.bind(this)})
      .then(() => {
        resolve();
      },  err => {
        reject(err);
      });
    });

    return processPromise;
  }
```

And this is my current skulpt version: https://github.com/waywaaard/skulpt/tree/epy_build

**Comment by albertjan** [comment]
so `__len__` sleep doesn't work on master currently I've attempted to correct it but the way the `canSuspend` argument is handled is so intricate that I haven't been able to fix it properly.

**Comment by albertjan** [comment]
PR for the sleepy len stuff's done now. Just need someone to merge it 😄

**Comment by eah13** [comment]
Thx for the upstream merge.  I've got writing client tests on my list and I'll write a bunch of those as part of merging this so we'll get a little bit of coverage against regressions.  Should be merged in a few days.

If you've got suggestions of things to zoom in on (or want to take a crack at the tests themselves), LMK!  Might ping you once or twice about the test framework if I get stuck.

**Comment by albertjan** [comment]
Cool yeah let me know if you run into something. I don't really know what you should pay attention at but probably the integrations is where things would break soonest.

**Comment by eah13** [comment]
Specific tests:

> skulpt#594 -> remapToPy() maps null to 'None' rather than '{}' (may break our ast module)

Tests pass, so seems good!

> skulpt#595 -> Better/More consistent handling of feedback. (does the checks feature use the setup function?)

Tests pass, so seems good!

> skulpt#598 -> More builtins (callable, next, iter)

Work beautifully.

> skulpt#597 -> Normalise implicit calls (moar suspendable stuff, check turtle suspension error)

Well, the error's changed at least.  [this example](https://trinket.io/python/2d6dbbe06c) gives "ExternalError: TypeError: Cannot read property 'slice' of undefined on line 2 in main.py"

> skulpt#600 -> Rename ParseError to SyntaxError (do we need to change something in wrapper for this?)

Nope! Works great.

**Comment by eah13** [comment]
Alright.  The issues above check out and I didn't see anything else that would be likely to cause regressions.  I'm going to merge and make a release for this so I can test against it and #41 together

Thx again! lots of goodies in here.

**Comment by albertjan** [comment]
This is so cool :)

**Pull request merged**
