### PR TITLE
Adjust yml

### PR DESCRIPTION
**Pull request by albertjan**
@eah13 one last one :)

### CODE REVIEW

**Comment by albertjan** [comment]
Oh I love automatic integration so much 😄

**Comment by brianpmarks** [comment]
@albertjan So is the idea with `dist-update.sh` to tag and push to trinketapp/skulpt-dist whenever something is pushed to trinketapp/skulpt#master?

How does tagging work? If I'm reading it correctly, it seems that a tag is added to trinketapp/skulpt-dist only when a new tag is added to trinketapp/skulpt. We don't currently add tags to trinketapp/skulpt but I guess we could. Especially if it automates the next step. :smiley:

Alternatively I guess we'd just manually tag trinketapp/skulpt-dist afterwards?

**Comment by eah13** [comment]
Ah yes, commit by commit we're getting there

**Comment by albertjan** [comment]
@brianpmarks yeah you have to tag the skulpt repo dist-update will update the tag on skulpt-dist. 

It wil also push to dist for every successful build on master. Without a tag.

**Comment by brianpmarks** [comment]
@albertjan Thanks.

So we should probably decide where to tag and where to update `bower.json`? I guess this repo makes the most sense (although we've not historically done either.) Although if I'm understanding things correctly, it seems that you'd have to quickly make a tag on trinketapp/skulpt immediately after pushing to master. Otherwise it seems like the tag won't be in place by the time travis gets around to pushing to trinketapp/skulpt-dist. Is that correct? If so, perhaps it's actually best to just wait and tag trinketapp/skulpt-dist after travis pushes?

**Comment by albertjan** [comment]
@brianpmarks I think you can push a tag before the commit. The script copies bower.json from skulp to dist. You never have to touch dist by hand again.

**Comment by brianpmarks** [comment]
@albertjan Yes, I like the idea of never having to touch dist. 👍 

Do you know how to push a tag before the commit? I thought a tag was tied to a specific commit. Regardless, this seems like a slightly new process. Rather than just merging PRs whenever we're ready, we'll need to prep the tag somehow first?

Thanks for getting me up to speed. Seems good to know how it's supposed to work. 😏

**Comment by brianpmarks** [comment]
In any event, for the moment, it looks like we'll need to manually tag something. Since this PR has already been merged I'll go ahead and tag trinketapp/skulpt-dist#master and then update the `bower.json` file in trinketapp/trinket#pygame-module.

**Pull request merged**
