### PR TITLE
Pull upstream

### PR DESCRIPTION
**Pull request by albertjan**
Oops I did it again! 😁 

- this contains a bunch of python3 fixes
- `__getattributes__` fixes 
- `set` operators

Thats it. Keeps us in lock step with upstream so we don't get behind too much. 

Also lets us pull in the PR's from meredydd which will give us an async read which will give us the possibility to get rid of our sync ajax request. 

Oh and this also gives me the possibility to pull in my PR from upstream that fixes the function descriptors. So I can add those weird static and instance functions in processing.py.

I've also added:

- super updates from upstream (so you can use `super` in the `__init__` of a class that inherits from a class that users `super` in the `__init__`)
- date bug
- relative imports fix
- `__get__` for function (that will need to change but it works for now)
- `re.compile` fix from upstream
- small `file` fixes

I fixed:

- async read and removed externalLibrary stuff
- print statement changes because of that

### CODE REVIEW

**Comment by eah13** [comment]
Looks good.  I had to update __future__ in wrapper.js with some of the new settings.  Got that in a branch for when this is released.

Speaking of which, can we get a version bump in bower.json?  Methinks that's all this needs for a merge.

**Comment by albertjan** [comment]
Yeah I’ll do a release PR to trinket. Should I include those other changes or do you want to ship this first and do a seperate release for those other skulpt changes.

________________________________

**Comment by eah13** [comment]
I'm happy to go ahead and release this unless you're planning on doing more releasable stuff over the weekend.

**Comment by albertjan** [comment]
adds some `super` fixes from upstream and the function descriptor I was talking about before.

**Comment by ANDEMEN** [comment]
@albertjan since externalLibrary stuff has been removed, how can i add externalLibrary?

**Comment by albertjan** [comment]
@ANDEMEN can you open an issue on http://github.com/skulp/skulpt 😄 I'll answer there.

**Pull request merged**
