### PR TITLE
Basic itertools.permutations implementation.

### PR DESCRIPTION
**Pull request by brianpmarks**
Works for simple cases (a list of numbers but **not any** iterable, e.g. a string) and "small" sets (any list with less than 6 elements seems to eventually finish but over that hangs the browser.)

Simple example that works in trinket (and in the unit test):

```
for p in permutations(range(1,4)):
  print p
```

The original example that spawned this specific work doesn't finish in the browser:

```
from itertools import permutations

solutions = 0
for a, b, c, d, e, f, g, h, i in permutations(map(float,range(1,10))):
    if round(a+13*b/c+d+12*e-f-11+g*h/i-10,10)==66:
        print (a,b,c,d,e,f,g,h,i)
        solutions +=1

print (solutions)
```

Perhaps there is a better implementation of the permutator function... I have seen a few implementations and will spend some time looking into them.

### CODE REVIEW

**Comment by brianpmarks** [comment]
A couple of other implementations didn't work any better on larger sets.

Looking now at what probably should be the real implementation anyway: generating a permutation at each iteration. Assuming it's possible, this'll cut down drastically on computation and memory needs.

**Comment by bzwheeler** [comment]
Cool, yeah, I think the python implementation can be fairly readily translated into javascript and would be something that could generate permutations on request.  I can take a stab at it if you would like.

**Comment by brianpmarks** [comment]
Sure, sounds good!

**Comment by bzwheeler** [comment]
Well I have a working javascript implementation, just gotta get it wired up as a skulpt generator...

```js
function permutations(iterable, r) {
  var list = iterable.slice(),
      n    = list.length,
      indices  = [],
      cycles   = [],
      res      = [],
      first    = true,
      done     = false,
      i, j,swap;

  r = r === undefined ? n : r;
  
  for (i = 0; i < n; i++) {
    indices[i] = i;
  }
  for (i = n+1; --i >= n-r+1;) {
    cycles.push(i);
  }

  var genResult = function() {
    return indices.map(function(v) { return list[v] });
  };

  return { 
    next : function() {
      if (first) {
        first = false;
        return genResult();
      }

      for (i = r; --i >= 0;) {
        cycles[i] -= 1;
        if (cycles[i] === 0) {
          indices = indices.slice(0,i).concat(indices.slice(i+1), indices.slice(i,i+1));
          cycles[i] = n - i;
        }
        else {
          j = cycles[i];
          swap = indices[i];
          indices[i] = indices[n-j];
          indices[n-j] = swap;
          return genResult();
        }
      }
      
      return undefined;
    }
  };
}

var n = permutations([0,1,2]);
var r = n.next();
while(r) {
  console.log(r);
  r = n.next();
}
```

**Comment by bzwheeler** [comment]
Doh! The python implementation actually worked with a minor change to not use the unimplemented `reversed` method.  Perhaps will still need to rewrite in js eventually as we implement the rest of `itertools` but this works great for now!

**Comment by bzwheeler** [comment]
The .js implementation I posted matches the python output exactly so if it comes down to needing to implement `itertools` in javascript, we should be able to use it.

**Comment by bzwheeler** [comment]
@brianpmarks - seems to work well with a python implementation, think we should just push that out?

**Comment by brianpmarks** [comment]
Cool, thanks! Interesting, though. I swear I tried the python implementation first but it just hung when called.

Regardless, fine with me to push it out. Can we push just this without the other latest Skulpt changes?

**Comment by bzwheeler** [comment]
Hmmm, I guess we have 2 options, we could make itertools a dynamically loaded library using the `externalLibraries` object and putting the file somewhere in our public directory or we could roll back to the previous working version of skulpt and rebuild a release from that...

**Comment by brianpmarks** [comment]
The first sounds a little easier. And I assume we could always fold it in to stdlib later. (I suspect there may be additional itertools methods requested in the near future.)

**Comment by bzwheeler** [comment]
Yeah, that seems like the path of least resistance.  I guess that means lets not merge this PR and open instead a PR against trinketapp/trinket for the time being.  At some point when we resolve the current Skulpt python2/python3 issue we can merge this into the stdlib.

**Comment by brianpmarks** [comment]
Sounds good. Unless you're already on it, I can take a stab at that.

**Comment by bzwheeler** [comment]
@brianpmarks: Go for it!

**Comment by bzwheeler** [comment]
BTW, a quick and non-comprehensive test revealed that `count`, `cycle`, `ifilter

**Comment by brianpmarks** [comment]
Closing for now in favor loading itertools via externalLibraries.

**Pull request closed without merging**
