### PR TITLE
SenseStick signal.pause() fix

### PR DESCRIPTION
**Pull request by waywaaard**
I've fixed the signal.pause(). Actually, it was my fault as I've though the key event of the sense stick is passed as a signal to the main thread.

### CODE REVIEW

**Comment by brianpmarks** [comment]
Nice! The example seems to work now!

I'm still having the problem where the joystick event listeners aren't working after the first run. In other words, I run the stick_test3.py example and everything seems to work. I stop the program and run it again but the joystick doesn't work. Would this be related? I don't experience the same thing with a program that doesn't use `signal.pause`.

Thanks for any thoughts on this.

**Comment by waywaaard** [comment]
I look into it. Maybe a listener or something is not being reset.

**Comment by brianpmarks** [comment]
False alarm! I believe I found the cause in how/when the joystick listeners are enabled on the trinket side of things. A fix for that is in trinketapp/trinket#1377 so I think this PR is good to go.

**Comment by waywaaard** [comment]
Ohh, cool. I just wanted to dig into this.

**Pull request merged**
