### PR TITLE
Implements first draft of compass, gyro and accel

### PR DESCRIPTION
**Pull request by eah13**
PR for discussion

### CODE REVIEW

**Comment by waywaaard** [comment]
## Examples for testing:


### Acceleration raw reading
```python
from sense_hat import SenseHat

sense = SenseHat()

sense.show_letter("J")

while True:
    x = sense.get_accelerometer_raw().['x']
    y = sense.get_accelerometer_raw().['y']
    z = sense.get_accelerometer_raw().['z']

    x = round(x, 0)
    y = round(y, 0)

    if x == -1:
        sense.set_rotation(180)
    elif y == 1:
        sense.set_rotation(90)
    elif y == -1:
        sense.set_rotation(270)
    else:
        sense.set_rotation(0)
```

```python
from sense_hat import SenseHat

sense = SenseHat()

while True:
    acceleration = sense.get_accelerometer_raw()
    x = acceleration['x']
    y = acceleration['y']
    z = acceleration['z']

    x = abs(x)
    y = abs(y)
    z = abs(z)

    if x > 1 or y > 1 or z > 1:
        sense.show_letter("!", text_colour=[255, 0, 0])
    else:
        sense.clear()
```

**Comment by waywaaard** [comment]
### Complete Test Example

Use the keydown (JoyStick) to switch through compass, accel and gyro

```python
from sense_hat import SenseHat, ACTION_RELEASED, DIRECTION_DOWN

sense = SenseHat()

def has_pushed_down():
  for event in sense.stick.get_events():
      if event.action == ACTION_RELEASED and event.direction == DIRECTION_DOWN:
        return True
  
  return False


sense.show_letter("G")
while True:
  gyro = sense.get_gyroscope_raw()
  print('gyro: ', gyro)
  if has_pushed_down():
    break

sense.show_letter("C")
while True:
  comp = sense.get_compass_raw()
  
  print('compass:', comp)
  if has_pushed_down():
    break

sense.show_letter("A")
while True:
    x = sense.get_accelerometer_raw()['x']
    y = sense.get_accelerometer_raw()['y']
    z = sense.get_accelerometer_raw()['z']
  
    print("gyro (raw) => x: %f y: %f z: %z" % (x, y, z))
  
    x = round(x, 0)
    y = round(y, 0)

    if x == -1:
        sense.set_rotation(180)
        print(180)
    elif y == 1:
        sense.set_rotation(90)
        print(90)
    elif y == -1:
        sense.set_rotation(270)
        print(270)
    else:
        print(0)
        sense.set_rotation(0)
    
    if has_pushed_down():
      break
    
print("Done")
```

**Comment by waywaaard** [comment]
Decouple the orientationChange event from the updating of the sense_hat.imu values.

Use a interval while skulpt is running and then periodically update the values.

**Comment by eah13** [comment]
@waywaaard: @albertjan  is going to build a skulpt-dist with his ffi stuff.  I'm leaning towards including this PR so we can have it all in one update.  Push now or forever hold your peace

**Comment by eah13** [comment]
@waywaaard Do we need to address these notes you left?

> Decouple the orientationChange event from the updating of the sense_hat.imu values.
> Use a interval while skulpt is running and then periodically update the values. Check if we can use the interval callback for noise creation

**Comment by waywaaard** [comment]
Already, done.

**Pull request merged**
